### PR TITLE
Edit configuration to new app version.

### PR DESCRIPTION
**Pull request by KacperLukasiewiczQA**
Newer android application changed the location of MainActivity. This causes our test to fail.

### CODE REVIEW

**Review by MarekPawlowskiQA — DISMISSED** [review]
lgtm :)

**Review by KlaudiaLapcionek — DISMISSED** [review]
lgtm

**Review by ospatrycja — DISMISSED** [review]
lgtm :)

**Review by ospatrycja — APPROVED** [review]
Lgtm :)

**Review by MarekPawlowskiAuto — APPROVED** [review]
ok :)

**Review by MarekPawlowskiQA — APPROVED** [review]

**Pull request merged**
