### PR TITLE
Add gitWorkflow.md file

### PR DESCRIPTION
**Pull request by KrzysztofGajQA**

### CODE REVIEW

**Review by MarekPawlowskiQA — DISMISSED** [review]
almost lgtm :)

**Comment by WDaniszewska** [comment]
Hi, space after hashtags should be added and a new line after the word "Branch",
I attach a preview of the file.
Changes

**Review by WDaniszewska — CHANGES_REQUESTED** [review]

**Review by WDaniszewska — APPROVED** [review]
Looks good to me

**Review by MarekPawlowskiQA — APPROVED** [review]
lgtm

**Pull request merged**
